### ISSUE TITLE
AncientPower bug

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#695] opened 2020-03-11 22:42 UTC
From @SoupPotato: In `AllUpHit`, `allstatsup` lacks a `statupmessage`, so AncientPower won't notify you when you get the stat boost.

**Comment by mid-kid** [comment] 2020-03-12 00:40
`statupmessage` and its counterpart `BattleCommand_StatUpMessage` only report the _last_ stat that's been raised. Move effects that affect multiple stats tend to call `BattleCommand_StatUpMessage` separately for each stat that's been raised, such as `BattleCommand_AllStatsUp` and `BattleCommand_Curse` do.
So, whatever the problem is, `statupmessage` is not the solution.

Furthermore, `allstatsup` already calls this function for every stat raised, and I've verified it on a clean repo that this works, at least on my machine. The problem is most likely somewhere in SoupPotato's modifications.

Closing until further notice.

**Closed by mid-kid** 2020-03-12 00:40 UTC
Labels: bug
