### ISSUE TITLE
Bug: Perish Song + Spikes = 0 HP Pokémon still battling

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#666] opened 2019-12-08 18:24 UTC
Pokémon A faints to Perish Song; you then switch to Pokémon B, who faints to Spikes. Except it doesn't faint, it just reaches 0 HP. It can take its next move before actually fainting, which even allows it to Recover and avoid fainting at all.

**Comment by mid-kid** [comment] 2019-12-08 18:58
Cursed issue

**Comment by coltongit** [comment] 2019-12-08 19:13
Does this occur in the original ROM?

**Comment by Rangi42** [comment] 2019-12-08 19:17
Yes, I'm reporting it here so we can design a minimal fix and document it.

**Comment by mid-kid** [comment] 2019-12-08 19:21
It'd help a lot to have a save file and/or save state (preferably for BGB) to test, since this is a thing that requires a bit of setup.

**Comment by coltongit** [comment] 2019-12-08 19:25
This would preferably require video for the bugs/glitches document. I'd be happy to implement it in my PR.

**Comment by coltongit** [comment] 2019-12-08 21:53
A fitting name for this glitch: Perish Song+Spikes zombie Pokemon glitch

**Comment by ISSOtm** [comment] 2019-12-09 13:01
I'm willing to debug this this afternoon. Is there a save state reproducing the bug available somewhere?

**Comment by coltongit** [comment] 2019-12-09 20:15
Someone on Discord has a save state that was posted earlier today.

**Comment by entrpntr** [comment] 2019-12-11 16:29
Just to clarify the bug, it is the interaction between the faint checks in HandleBetweenTurnEffects and SpikesDamage (which only subtracts HP on a Pokémon's entrance, and doesn't handle fainting conditions).

For instance, say you have a full party at 1 HP and spikes up, and Pokémon A faints to Sandstorm damage in "HandleWeather". Pokémon B will faint after taking spikes damage from the check after "HandleWrap", Pokémon C will faint from the check after "HandlePerishSong", but Pokémon D will survive on 0 HP.

**Comment by coltongit** [comment] 2019-12-11 16:30
A fix for this issue is in PR #664.

**Closed** 2020-01-04 21:57 UTC
