### ISSUE TITLE
Document that the 6-bit caught level can only record up to level 63

### ISSUE THREAD

**Issue by Rangi42** [pret/pokecrystal#901] opened 2022-04-04 23:52 UTC
This could go in docs/design_flaws.md, but there's no simple fix (the other bits are all used), so maybe a comment next to `CAUGHT_LEVEL_MASK` would be enough. (Note that Lugia and Ho-Oh are level 60, not 70, possibly for this reason.)

**Comment by vulcandth** [comment] 2022-04-25 13:04
Unless I am missing something, upon looking over this it doesn't seem too bad to fix. `MON_CAUGHTLEVEL` is whole byte.. which should be plenty. The problem is the Pokémon seer stores this value in a temporary byte `wSeerCaughtData` (along with Caught Time) before loading it into `wSeerCaughtLevel`. I haven't yet figured out the reason for the intermediate step... but it could be as simple as skipping the intermediate step.. or adding an extra temp byte. I'll work on this a bit later, since i'm re-adding Ho-Oh and Lugia to my Rom-hack at level 70.

**Comment by Rangi42** [comment] 2022-04-26 20:35
No, the other two bits in that byte are used for the caught time (morning, day, night, or unknown).

```
CAUGHT_TIME_MASK  EQU %11000000
CAUGHT_LEVEL_MASK EQU %00111111

CAUGHT_GENDER_MASK   EQU %10000000
CAUGHT_LOCATION_MASK EQU %01111111
```

**Comment by vulcandth** [comment] 2022-05-01 01:15
Okay; so I found a fix for this... It's probably not super efficient.. but it works. (I am still learning asm after all). Perhaps it can give someone an idea to make it more efficient. I have tested it in game, it does work.

Modify `CAUGHT_LEVEL_MASK` in `constants\pokemon_data_constants.asm` 
```diff
 CAUGHT_TIME_MASK  EQU %11000000
-CAUGHT_LEVEL_MASK EQU %00111111
+CAUGHT_LEVEL_MASK EQU %01111111
```

Modify `ReadCaughtData` in `engine\events\poke_seer.asm` 
```diff
 ReadCaughtData:
+	ld a, MON_CAUGHTLEVEL
+	call GetPartyParamLocation
+	ld a, [hl]
+	and CAUGHT_LEVEL_MASK
+	ld [wSeerCaughtLevel], a
	ld a, MON_CAUGHTDATA
	call GetPartyParamLocation
	ld a, [hli]
	ld [wSeerCaughtData], a
	ld a, [hld]
	ld [wSeerCaughtGender], a
	or [hl]
	jr z, .error
```

Modify `GetCaughtLevel` in `engine\events\poke_seer.asm` 
```diff
 GetCaughtLevel:
 	ld a, "@"
	ld hl, wSeerCaughtLevelString
	ld bc, 4
	call ByteFill

	; caught level
-	; Limited to between 1 and 63 since it's a 6-bit quantity.
-	ld a, [wSeerCaughtData]
-	and CAUGHT_LEVEL_MASK
+	ld a, [wSeerCaughtLevel]
+	cp 0
	cp CAUGHT_EGG_LEVEL ; egg marker value
	jr nz, .print
	ld a, EGG_LEVEL ; egg hatch level

.print
-	ld [wSeerCaughtLevel], a
	ld hl, wSeerCaughtLevelString
	ld de, wSeerCaughtLevel
	lb bc, PRINTNUM_LEFTALIGN | 1, 3
```

**Comment by Rangi42** [comment] 2022-05-01 01:25
No, that reuses a bit already used by `CAUGHT_TIME_MASK`.

**Comment by vulcandth** [comment] 2022-05-01 01:28
> No, that reuses a bit already used by `CAUGHT_TIME_MASK`.

No, I don't have that problem anymore, since i'm not storing the value in `wSeerCaughtData`. I'm storing the value directly in `wSeerCaughtLevel`.

**Comment by Rangi42** [comment] 2022-05-01 01:36
```
CAUGHT_TIME_MASK  EQU %11000000
CAUGHT_LEVEL_MASK EQU %00111111

CAUGHT_GENDER_MASK   EQU %10000000
CAUGHT_LOCATION_MASK EQU %01111111
```

4 times (morn, day, night, unknown) fit in 2 bits. 64 levels (0 to 63) fit in 6 bits. They share an 8-bit byte.

2 genders (boy or girl) fit in 1 bit. 128 locations (96 actually used, plus 2 for event and gift mons) fit in 7 bits. They share an 8-bit byte.

By storing the caught level directly in `wSeerCaughtLevel`, you're potentially corrupting the caught time stored in its high 2 bits.

**Comment by Idain** [comment] 2022-05-01 01:47
I agree with Rangi on this. You only changed the bitmask but not how the data is being stored.

**Comment by vulcandth** [comment] 2022-05-01 02:23
Thanks! I understand the greater problem now.

**Comment by Asday** [comment] 2022-05-02 03:19
> This could go in docs/design_flaws.md

Is it actually a design flaw?  It seems to me more of a (game) design consideration, or something arising from the preextant game design.  In the former, the game designers have to plan the level curve of progressing areas around the max of 63, which, with the maximum being 60, seems reasonable.  In the latter, the highest level was found to be 60, and they found a few bits here and there that they could use to store just a little bit more than 60.

**Comment by Rangi42** [comment] 2022-05-02 03:58
It's a design flaw for the same reason that the level 1 experience underflow bug is a bug: levels go from 1 to 100, there's no fundamental reason those shouldn't work.

**Comment by Asday** [comment] 2022-05-02 04:04
From which perspective?  As you very correctly said

> there's no simple fix

so from the technical side there's a fundamental reason, and from the game design side there's no wild mon with a level high enough to need it to work differently.  They weren't writing a general purpose game engine, they were writing Pokémon Crystal, after all.  Add to that the extra bits in the data were used for other information, it seems like a really elegant use of spare space, rather than a design flaw.

**Comment by Rangi42** [comment] 2022-05-02 04:42
The design flaws are described for people editing/hacking the source for their own projects. For them, this could be an issue.

**Comment by Asday** [comment] 2022-05-02 04:51
Gotcha, I'm getting hung up on the filename.

**Comment by vulcandth** [comment] 2022-05-13 14:41
I have a bit of a suggestion... Why don't we actually add this into `docs/design_flaws.md`, but instead of providing a fix, we describe the problem, and offer a couple suggestions users may look into to resolve the problem. I think knowing what the problem is, in a bit of detail, can also be pretty useful, even if it doesn't provide a fix.

Basically the precedent would be that if we don't provide an actual fix, we describe the problem and offer a couple suggestions. These suggestions could be a simple bullet list of things user's could look into to fix the problem.

One of the suggestions for this would be something like : 
* A possible solution would be to repurpose a free bit from one of the following: MON_LEVEL (1 free bit),  MON_EXP (3 free bits), ect...

**Closed** 2022-07-09 18:39 UTC
Labels: bug docs
